### ISSUE TITLE
Kotlin Multiplatform Support

### ISSUE THREAD

**Issue by ScottPierce** [MayakaApps/LruKache#19]
The community needs a good multiplatform LRU implementation. This library seems like it's got a good base for it. I actually noticed in the source that you were playing around with multiplatform. I thought I'd add this ticket to track the work.

**Comment by ScottPierce** [comment]
@MSDarwish2000 I'm not entirely sure why you are adding multiplatform stream support and other things like that, but okio has a multiplatform implementation and I think they also have support for encryption / hashing multiplatform also.

**Comment by ScottPierce** [comment]
This would also allow you to support other platforms like js, and get a full multiplatform LRU library where almost all logic was in `common`.

**Comment by MSDarwish2000** [comment]
Thank you for opening the issue for me. I appreciate your interest and suggestions. And yes, I'm working on going multiplatform supporting all platforms, but I've decided to start with Apple's platforms as the main goal is to support Kotlin Multiplatform Mobile.

As for the IO implementation, I wasn't sure if I should depend on OKIO or implement a lightweight IO classes to keep the library binaries as small as possible.

For me, it was like:

- Depend on OKIO: as most KMP projects will be depending on OKIO, so there is no increase in binary size. Also, OKIO is well maintained and tested.
- Implement lightweight IO classes: to keep binaries as small as possible and use native IO methods directly. Also, it wasn't that hard for me, at least till now.

I'm still hesitated and may switch to OKIO before v2.0.0 release.

As a side point, I'm thinking of changing the library name as well to make it obvious that it is not just Kotlin/JVM version of the well-known libraries, so any suggestions are welcome. 😊

**Comment by ScottPierce** [comment]
> I'm thinking of changing the library name as well

I think that makes sense. I'm not sure what the naming scheme is that the community will eventually settle on, but `kotlin-lru-cache` with "Kotlin Multiplatform" spelled out cleary in the description is pretty safe. The super verbose approach would be `kotlin-multiplatform-lru-cache`.

> As for the IO implementation
Depend on OKIO: as most KMP projects will be depending on OKIO, so there is no increase in binary size. Also, OKIO is well maintained and tested.

For a lot of people IO isn't even necessary for their use case. i.e. I came looking just for something similar to Androids memory based LRU cache. Disk based LRU caches are more niche. **I'd definitely ship at least 2 different artifacts, one for the memory-only version, and the other with a plugin / wrapper for disk based caching.**

For anything that requires IO, I'd be scared to trust anything except okio.

**Comment by MSDarwish2000** [comment]
Thank you for this suggestion. You're right that memory-only version deserves a separate artifact. Also, after re-thinking about Okio, It appears that I should have used it from the start, especially that it is the recommended library for IO by JetBrains. 

I'll be doing exactly as you've suggested. Starting by separating the artifacts so that the memory-only artifact be stable enough to be tested as a multiplatform snapshot version.

Then I'll be migrating to Okio, continuing tests and fixes phase for DiskLruCache as the current snapshot version of it is still unusable and the journal needs more operations (READ operation and DIRTY_REMOVE operation).

**Comment by MSDarwish2000** [comment]
If you want, you can create separate issues for separate artifacts and Okio migration. If not, I'll be doing this later today or tomorrow, when I continue to work on the library.

**Comment by MSDarwish2000** [comment]
I've already migrated the library to become multiplatform, use separate artifacts, and use Okio. This can already be tested in the latest snapshot version. I've also renamed the library as well.

More changes to the library are planned before stable release. These changes include updating the journal, and adding test coverage for DiskLruCache. Other changes that I'm not sure about is whether to expose an API that depends on Okio or not. Finally, documentation will be updated throughout the API.

For now, I'm closing the issue. Feel free to share any new suggestions or bug reports.

**Comment by ScottPierce** [comment]
Thank you for doing this for the community!

**Comment by ScottPierce** [comment]
@MSDarwish2000 I like the name you chose :D

**Comment by MSDarwish2000** [comment]
Oh! That's nice of you ❤️
